ParameterScale: 1
NetworkExpansion: 1
Trans_Loss_Segments: 1
UCommit: 2
CO2Cap: 1
MaxCapReq: 1
MinCapReq: 1
CapacityReserveMargin: 1
StorageLosses: 1
PrintModel: 1
WriteShadowPrices: 1
OverwriteResults: 1
