WriteCosts: false
WriteCapacity: false
WriteCapacityValue: false
WriteCapacityFactor: false
WriteCharge: false
WriteChargingCost: false
WriteCO2: false
WriteCO2Cap: false
WriteCommit: false
WriteCurtailment: false
WriteEmissions: false
WriteEnergyRevenue: false
WriteESRPrices: false
WriteESRRevenue: false
WriteFuelConsumption: false
WriteHourlyMatchingPrices: false
WriteHydrogenPrices: false
WriteMaintenance: false
WriteMaxCapReq: false
WriteMinCapReq: false
WriteNetRevenue: false
WriteNSE: false
WriteNWExpansion: false
WriteTransmissionFlows: false
WriteTransmissionLosses: false
WriteVirtualDischarge: false
WriteVREStor: false