WriteCosts: true
WriteCapacity: true
WriteCapacityValue: true
WriteCapacityFactor: true
WriteCharge: true
WriteChargingCost: true
WriteCO2: true
WriteCO2Cap: true
WriteCommit: true
WriteCurtailment: true
WriteEmissions: true
WriteEnergyRevenue: true
WriteESRPrices: true
WriteESRRevenue: true
WriteFuelConsumption: true
WriteHourlyMatchingPrices: true
WriteHydrogenPrices: true
WriteMaintenance: true
WriteMaxCapReq: true
WriteMinCapReq: true
WriteNetRevenue: true
WriteNSE: true
WriteNWExpansion: true
WriteTransmissionFlows: true
WriteTransmissionLosses: true
WriteVirtualDischarge: true
WriteVREStor: true