NetworkExpansion: 0
TimeDomainReductionFolder: "TDR_Results"
ParameterScale: 1
EnergyShareRequirement: 0
PrintModel: 1
TimeDomainReduction: 0
Trans_Loss_Segments: 1
CapacityReserveMargin: 0
MethodofMorris: 0
Reserves: 0
StorageLosses: 1
OverwriteResults: 0
UCommit: 2
ModelingToGenerateAlternatives: 0
MaxCapReq: 0
MinCapReq: 0
CO2Cap: 0
WriteShadowPrices: 1
HydrogenHourlyMatching: 1
