ParameterScale: 1
NetworkExpansion: 1
Trans_Loss_Segments: 1
UCommit: 2
StorageLosses: 1
CO2Cap: 1
MinCapReq: 1
CapacityReserveMargin: 1
EnergyShareRequirement: 0
VirtualChargeDischargeCost: 1
PrintModel: 1
WriteShadowPrices: 1
