name: CI

on: 
  pull_request:
  push:
    branches: [main, develop]
    tags: ['*']
    
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name}}
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix:
        version:
          - "1.6" # LTS (64-bit Linux)
          - "1.7"
          - "1.8" 
          - "1.9" 
          - '1'  # latest stable Julia release (Linux)
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - name: Commit logs and push to repo
        if: ${{ matrix.version }} == '1.9'
        run: |
          echo ${{ matrix.version }}
          if [[ ${{ matrix.version }} == '1' ]]; then
            git config --local user.name lbonaldo
            git config --local user.email "bonaldo.luca12@gmail.com"
            git checkout ${GITHUB_REF#refs/heads/}
            git checkout -b ${GITHUB_REF#refs/heads/}-testlogs
            git add -f test/Logs
            git commit -m "Test logs updated"
            git push origin ${GITHUB_REF#refs/heads/}-testlogs
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
