name: Test-CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.9"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          annotate: true
      - name: Test an example case
        shell: julia --project=downstream {0}
        run: |
          include("Example_Systems/SmallNewEngland/OneZone/Run.jl")